package com.servlet;

import java.io.IOException;

import com.servlet.h2.FileRepository;
import org.eclipse.jetty.server.Server;

import org.eclipse.jetty.server.handler.ErrorHandler;
import org.eclipse.jetty.servlet.ServletContextHandler;
import org.eclipse.jetty.servlet.ServletHolder;
import org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher;

public class WebServer {

    public static void main(String[] args) throws IOException {
        int port = 9090;
        Server server = new Server(port);
        ServletContextHandler context = new ServletContextHandler(ServletContextHandler.SESSIONS);
        context.setContextPath("/");
        ServletHolder holder = new ServletHolder(new HttpServletDispatcher());
        holder.setInitParameter("javax.ws.rs.Application", "com.servlet.resteasy.RestComponentsScanner");
        context.addServlet(holder, "/v2/*");

        ErrorHandler errorHandler = new FileApiErrorHandler();
        context.setErrorHandler(errorHandler);

        context.addServlet(ServletFileController.class, "/*");
        server.setHandler(context);

        initH2Sql();
        try {
            server.start();
            server.join();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    static void  initH2Sql() {
        new FileRepository().getJtm().execute(
                "CREATE TABLE file_info (" +
                        "    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL," +
                        "    name      VARCHAR(255)," +
                        "    size BIGINT," +
                        "    type VARCHAR(255)" +
                        "); "
        );
    }
}
